### ISSUE TITLE
Using My Own Fonts.

### ISSUE THREAD

**Issue by Zecrobar** [ItsPriyesh/Fontster#22]
Hello, I really like the app above other font changing apps as it has the different types of a font. Just that I want to use a font that I've downloaded, I have the regular, bold, italics and bold italics of the font. How do I go about doing so?

**Comment by ItsPriyesh** [comment]
You can install your own font files, but it's experimental and slightly dangerous. Installing invalid font files can cause your phone to bootloop, so I would recommend making a backup first or having the [flashable stock font zip](https://github.com/ItsPriyesh/FontsterFontsRepo/blob/1d1fd6c2b0dd28943c8e1c8c93ff35ba3c3e530b/RestoreStockFonts.zip) handy.

Open Fontster then go to its settings. Tap on 'App version' 8 times, and Developer settings will open. From there you can click on 'Install custom font'.

**Comment by draeath** [comment]
Why is this so hidden away? That seems a bit extreme.

So, is this just replacing the Roboto fonts in /system/fonts then?

**Comment by ItsPriyesh** [comment]
Currently I don't do any sanity checks on the files that the user selects. So if someone decides to pick invalid font files, the phone will get stuck in a bootloop. Even if I have a prominent warning, I'm sure countless users will ignore it, soft brick their phone, and end up complaining to me. So I think it's best to keep this feature hidden away for now. At least until I make it more robust.

Yes, it works using the same installation mechanism as the prebuilt font packages. You can find further details in FontInstaller.java

**Comment by Fabian42** [comment]
For anyone (like me) finding this report much later: The restoration zip will likely not work, since it tries to unpack to `/system/fonts`. At least on my phone, fonts are in `/product/fonts`. It also mentions KitKat and the Play store link is broken, so I guess that this project is abandoned.
