### ISSUE TITLE
Font changed for Web pages, but not for UI

### ISSUE THREAD

**Issue by paulcanning** [ItsPriyesh/Fontster#4]
As title, I changed the font but it's only apparent in Web pages, and non of the system UI has changed. I have the stock font in all my settings, keyboard etc. 

Running an OPO on CM11

**Comment by paulcanning** [comment]
Any reason for closing it? Has it been fixed?

**Comment by paulcanning** [comment]
Nevermind, I see why it's not been fixed. And I doubt you'll fix it. 

Just tried on v2.2 and UI fonts are still not working. 

Gonna try someone else's app.

**Comment by ItsPriyesh** [comment]
Sorry I assumed that I had fixed the issue after the full rewrite of the app.
Does the installation of the font go through without any errors? Could you get a log of the app during an installation. Thanks.

**Comment by paulcanning** [comment]
I updated to v2.3, and still not working.

The font downloaded fine, installed fine and when I rebooted, the font in the browser had changed (so on a website, like facebook.com, the font was different) but the UI font hadn't changed,

Changing the font with CM theme engine worked.

But I have just updated to Lollipop now, so I may not be able to get you the logs you need.
