### ISSUE TITLE
Error Making Project From Source In Android Studio

### ISSUE THREAD

**Issue by DaniApps** [ItsPriyesh/Fontster#7]
Hey ! Thanks for the sources, i am trying to make project and project getting build but its throwing error  while generating APK or making project. Below is the error i am getting. 
 Error:javac: invalid flag: S\Documents\GitHub\Fontster\app\build\retrolambda\debug
 Usage: javac <options> <source files>
 use -help for a list of possible options
Error:Execution failed for task ':app:_compileDebugJava'.
> Compilation failed with exit code 2; see the compiler error output for details.

**Comment by ItsPriyesh** [comment]
Make sure you have the language level of the project set to Java 8 by including the compileOptions block in your build.gradle. Also check that you have the JDK 8 installed.

**Comment by DaniApps** [comment]
Have installed the jdk 8 already and have already added the compile options. Below is the mid part of the build.gradle.. 

apply plugin: 'retrolambda'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.chromium.fontinstaller"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 20
        versionName "2.5"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
}

retrolambda {
    jdk 'C:\\Program Files\\Java\\jdk1.8.0_45'
    oldJdk 'C:\\Program Files\\Java\\jdk1.7.0_71'
    javaVersion JavaVersion.VERSION_1_6
}
